### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by mastershare95** [bgregs514/vscode-tm1#23]
Hello,

1. When I try to use Add new connection function it redirect me to defaultConnection settings, I cant' connect to TM1 server
![image](https://user-images.githubusercontent.com/51332636/112151945-110f0980-8be2-11eb-83a5-803d0d2fcdfd.png)

2. Then the vscode doesn't let me know if I'm connected or my connection is invalid
![image](https://user-images.githubusercontent.com/51332636/112152276-69460b80-8be2-11eb-90d2-a32e73d3b0ae.png)

3. Even the list doesn't update after reload button, reload update command or restarting vscode
![image](https://user-images.githubusercontent.com/51332636/112152429-95fa2300-8be2-11eb-9f72-7a1e990d1884.png)

Please let me know what is causing the bug or maybe I'm just using the extension in a wrong way.

**Comment by bgregs514** [comment]
Hi @mastershare95, thanks for taking the time to check out the extension!  The "Connection List" is still very much a work in progress and is more of a placeholder at this point.

Once the settings are entered, you can reprocess them by clicking the "refresh" wheel in the "TM1 Connections" pane, and everything should begin to initialize.  Aside from that, that's really all we currently have in place as far as connection info goes.  We are actively working on making these features more robust, but currently we have a few other areas that are our main focus right now (workflow, TI run with parameters, etc.).

If you're running the extension in debug mode (compared to installing the .vsix file), there are some helpful debug lines related to connection info.  Unfortunately we are still very much at a work in progress stage, so some of these things will take time to fully polish.  If you notice anything that you think could be reworked to flow better, or any features that would improve quality of life while using the extension, please share them with us!

Documentation is a high priority right now, and I will do my best to get something released that demonstrates exiting features and how to use them.

**Comment by mastershare95** [comment]
Hi, @bgregs514  thank you for your detailed answer but I think that we didn't understand each other correctly, I have the version of the extension but in my specific case it seems that all features are not working. Only the  Add new Connection is function is redirecting me to the defaultCcnnection settings window but after that is not working correctly. As well I have tried to create a process (as shown in the gif video) but to me, it is working as a blank function.
Please let me know what can I try to do to start using this really useful extension.

**Comment by bgregs514** [comment]
@mastershare95 - If you are seeing functions that aren't running, that would be a sign that the connection to the TM1 instance is not setup correctly.  If you run the extension in debug mode (the current recommend way), you should get much more detailed debug messages that will point you in the right direction.

It is possible that this is a bug, but given that this is the only case I have heard of I would recommend that we close this issue and reopen it as a QA on the discussion page of the project.
