### ISSUE TITLE
Support of shortcut (ctrl + s) for saving an object

### ISSUE THREAD

**Issue by ichermak** [bgregs514/vscode-tm1#26]
**Describe the solution you'd like**
It would be nice if we can use shortcut (ctrl + s) to save an object.

**Comment by bgregs514** [comment]
I agree that we need a shortcut for pushing to the server, but I don't think overriding the default ctrl + s functionality would be ideal in this case.  At it's core, all the extension is doing is modifying local copies of files.  In the most traditional sense, a ctrl + s should just save the file.

For example, I use ctrl + s after every few words I type just so I don't lose progress.  If the extension attempted to push code every time I hit the shortcut, it would result in bad code pushing up.  I could also see a case where a developer could be working on multiple files (find a replace scenario) and want to do a batch push once all of their updates are finished.  In this case, I think a dedicated shortcut to deliberately push would be a better option.

What I'm proposing is something like ctrl + shift + s (or something similar) to both save the file, and push to the server.  This way it leaves the ctrl + s workflow intact in case people like me use it way too much while typing. 😉

Would that work alright for your use case?

**Comment by bgregs514** [comment]
`ctrl + shift + s` shortcut is now available as an additional way to save tm1 objects to a tm1 server.
