### ISSUE TITLE
Update Syntax Colors

### ISSUE THREAD

**Issue by bgregs514** [bgregs514/vscode-tm1#3]
Either something went wrong when I merged the tm1helper language files into the project, or they never looked like they did in the project pages screenshot, but the color scheme could probably use some rework.  Right now things are tinted a sort of yellow color, and I would prefer to have some cleaner, bolder colors to distinguish between operators/functions/etc.

**Comment by scrumthing** [comment]
We could go one step further and use different highlighting for useful and rather useless functions like ForceSkipCheck() 🙃. 
Since IBM will not remove those functions, we could give them a different color and could make the decision a community voting. 
What do you guys think?

**Comment by bgregs514** [comment]
@scrumthing Good point!  I'm going to convert this issue to a discussion.  Once we're settled on colors, themes, and paths forward we can pull the finalized proposal back over as an enhancement.  Thanks!
