### ISSUE TITLE
Unable to add connection

### ISSUE THREAD

**Issue by ichermak** [bgregs514/vscode-tm1#31]
**Describe the bug**
Unable to add connection. When clicking on the "Add a new connection" button, nothing happens. 
I have also tried to modify the settings as shown below and refreshing the page ... without success!

![Capture](https://user-images.githubusercontent.com/33223981/120982864-71413080-c779-11eb-9f36-20f8a96d16f1.PNG)

**Expected behavior**
Access to the TM1 instance objects.

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/33223981/120983087-a8afdd00-c779-11eb-8728-3bcc87b3b4b1.PNG)

**Comment by bgregs514** [comment]
Closed - this has been discussed, resolved, and explained multiple times in both closed issues and discussions.

Please see: #22
